### PR TITLE
Literature comparison heatmap

### PR DESCRIPTION
**Pull request by lagillenwater**
Example test script with : 
`Rscript literature_comparison_heatmap.R --input_file "~/Downloads/literature_comparison_evaluation_with_IDF 2.csv" --\output_directory ./heatmaps/`

** input_file doesn't require quotes if the file name is a single string

### CODE REVIEW

**Comment by bsantan** [comment]
The new R library will need to be added to the environment. I'm having trouble installing on the fly, it wants me to pick a CRAN mirror and then said "1: package ‘ComplexHeatmap’ is not available for this version of R" and I have R version 4.1.2 (2021-11-01), do I need a different version?

**Comment by lagillenwater** [comment]
Updates:
- environment.yml includes r (version 4.2.1) and r packages
- literature_comparison_heatmap.R installs ComplexHeatmap via bioconductor

**Comment by bsantan** [comment]
I got this error:

Error in library(ComplexHeatmap) : 
  there is no package called ‘ComplexHeatmap’
Execution halted

**Comment by lagillenwater** [comment]
Did you get any other output?

**Review by bsantan — APPROVED** [review]

**Pull request merged**
