### PR TITLE
New node exclusion

### PR DESCRIPTION
**Pull request by bsantan**
It was difficult to break this task up, so this is a large commit.

1. support for edge and node exclusion in graph object, edgelist, and labels dfs
2. always use networkx methods, though when igraph is specified by changing the method in create_graph, it will work
3. simplify functions to only pass graph class, rather than individually graph object, edgelist, and labels

To test, run ./test_script.sh. You can modify the WP4535_output/_annotated_diagram_Input_Nodes_.csv file to have fewer lines for a quicker test.

### CODE REVIEW

**Comment by lagillenwater** [comment]
I got this error: 

`Traceback (most recent call last):                                                                             
  File "/Users/lucas/Library/CloudStorage/OneDrive-TheUniversityofColoradoDenver/Projects/Cartoomics/creating_ 
subgraph_from_KG.py", line 11, in <module>                                                                     
    from memory_management import *                                                                            
  File "/Users/lucas/Library/CloudStorage/OneDrive-TheUniversityofColoradoDenver/Projects/Cartoomics/memory_ma 
nagement.py", line 23, in <module>                                                                             
    import psutil                                                                                              
ModuleNotFoundError: No module named 'psutil'                                                                  `

Are you using any of the memory_management stuff?

**Comment by bsantan** [comment]
@lagillenwater I'm not using memory management, but do you need that for alpine? Otherwise I can comment that line out and commit to this branch

**Comment by lagillenwater** [comment]
@bsantan I don't think we need memory management in alpine anymore, since the networkx fix

**Comment by lagillenwater** [comment]
Works great with commented out psutil

**Pull request merged**
