### PR TITLE
43 get wikipathways data in graph format from pfocr

### PR DESCRIPTION
**Pull request by lagillenwater**
Added:
- wikipathways_converter.py 
- wikipathways_mod.py

Runnining "python wikipathways_converter.py --wikipathways WPXXXX will produce 4 outputs in the current directory:
- WPXXX_datanodeDF.csv
- WPXXX_edgeList.csv
- WPXXX_graph.graphml
- WPXXX_interactDF.csv

### CODE REVIEW

**Comment by bsantan** [comment]
Need to update environment to install bio services

**Comment by lagillenwater** [comment]
This error is related to the environment file. Update the environment file so that it works in a reproducible manner across systems

**Comment by lagillenwater** [comment]
The problem is with wikinetworks, networkx,  numpy, and csgraph

wikinetworks requires networkx == 2.4
networkx==2.4 does not work with numpy > 1.19.5
csgraph needs numpy>=1.21

potential workaround: install packages individually instead of install wikinetworks>=1.1.2

**Comment by lagillenwater** [comment]
Test by running 'wikpathways_test_script.sh'. If it works, we can delete this test script.

**Review by bsantan — APPROVED** [review]

**Pull request merged**
